### PR TITLE
add sync block for thread safety around state that needs multi-thread protection

### PR DESCRIPTION
**Pull request by amarkowitz**
references https://github.com/looker/helltool/issues/33620

### CODE REVIEW

**Review by conrizzle — APPROVED** [review]
🚀 🚢

**Comment by conrizzle** [comment]
Corresponding HT PR coming soon?

**Comment by amarkowitz** [comment]
Supposedly the gemfile.lock will notice the difference between the commit hash it has and the new commit hash for this branch and everything will just work.  Going to verify after I push :)

**Comment by amarkowitz** [comment]
yes

**Pull request merged**
